#!/usr/bin/env python3
# -*- coding:utf-8 -*-

import re

shiftRule =[(re.compile("((?<=</ENTITY_num>)|(?<=</QUANTIFIER>))<ENTITY_noun>身</ENTITY_noun>"),("ENTITY_noun",),("ENTITY_classifier",)),
            (re.compile("(<FUNC_inter>無</FUNC_inter>)<QUANTIFIER>歸</QUANTIFIER>"), ("QUANTIFIER",), ("ACTION_verb",)),
            (re.compile("<FUNC_inter>無</FUNC_inter>((?=<ACTION_verb>)|(?=<MODIFIER>)|(?=<MODAL>))"),("FUNC_inter",),("FUNC_negation",)),
            (re.compile("<FUNC_negation>無</FUNC_negation>(<ACTION_verb>會</ACTION_verb>)"),("FUNC_negation",),("FUNC_inter",)),           
            (re.compile("(?<=[^<愛知做得]</ACTION_verb>)<ACTION_verb>[好等]</ACTION_verb>"), ("ACTION_verb",), ("ASPECT",)),
            (re.compile("<ACTION_verb>識</ACTION_verb>(?=<ACTION_verb>)"), ("ACTION_verb",), ("ASPECT",)),
            (re.compile("<MODIFIER>緊</MODIFIER>(?=<ACTION_verb>)"),("MODIFIER",),("TIME_justtime",)),
            (re.compile("<FUNC_inter>無</FUNC_inter>$"),("FUNC_inter",),("CLAUSE_Q",)),
            (re.compile("<MODIFIER>大</MODIFIER><ACTION_verb>聲</ACTION_verb>"),("<MODIFIER>大</MODIFIER><ACTION_verb>聲</ACTION_verb>",), ("<MODIFIER>大聲</MODIFIER>",)),
            (re.compile("(<FUNC_degreeHead>恁</FUNC_degreeHead>)<ENTITY_noun>[垃圾牛冰]</ENTITY_noun>"),("ENTITY_noun",), ("MODIFIER",)),        
            (re.compile("(<FUNC_degreeHead>恁</FUNC_degreeHead>)<ENTITY_classifier>重</ENTITY_classifier>"),("ENTITY_classifier",), ("MODIFIER",)),        
            (re.compile("<FUNC_degreeHead>[恁當蓋]</FUNC_degreeHead><MODIFIER>[^<]+</MODIFIER>"),("<FUNC_degreeHead>", "</FUNC_degreeHead><MODIFIER>", "</MODIFIER>"), ("<DegreeP>", "", "</DegreeP>")),
            (re.compile("<FUNC_inter>無</FUNC_inter>(?=<DegreeP>)"),("FUNC_inter",),("FUNC_negation",)),
            (re.compile("</MODIFIER_color><MODIFIER_color>"), ("</MODIFIER_color><MODIFIER_color>",), ("",)),
            (re.compile("<FUNC_inner>還</FUNC_inner><MODIFIER>[^<]+</MODIFIER>"),("<FUNC_inner>", "</FUNC_inner><MODIFIER>", "</MODIFIER>"), ("<DegreeP>", "", "</DegreeP>")),
            (re.compile("(<ENTITY_num>一</ENTITY_num>)<ACTION_verb>領</ACTION_verb>"), ("ACTION_verb",), ("ENTITY_classifier",)),
            (re.compile("(?<=</ENTITY_num>)<ENTITY_noun>個人</ENTITY_noun>"),("<ENTITY_noun>個人</ENTITY_noun>",), ("<ENTITY_classifier>個</ENTITY_classifier><ENTITY_noun>人</ENTITY_noun>",)),
            (re.compile("<ENTITY_num>[^<]+</ENTITY_num><ENTITY_classifier>[^<]+</ENTITY_classifier>"), ("</ENTITY_num><ENTITY_classifier>", "ENTITY_num"), ("", "ENTITY_classifier")),
            (re.compile("<ENTITY_num>[^<]+</ENTITY_num><ENTITY_noun>尺</ENTITY_noun>"), ("ENTITY_noun",), ("ENTITY_measurement",)),
            (re.compile("<ENTITY_num>[^<]+</ENTITY_num><ENTITY_measurement>[^<]+</ENTITY_measurement>"), ("</ENTITY_num><ENTITY_measurement>", "ENTITY_num"), ("", "ENTITY_measurement")),
            (re.compile("<ACTION_verb>([^<])</ACTION_verb><ACTION_verb>\\1</ACTION_verb>"), ("</ACTION_verb><ACTION_verb>",), ("",)),
            (re.compile("<ACTION_verb>講</ACTION_verb><ACTION_verb>話</ACTION_verb>"), ("</ACTION_verb><ACTION_verb>",), ("",)),
            (re.compile("(?<=</FUNC_degreeHead>)<ACTION_verb>好</ACTION_verb>"), ("ACTION_verb",), ("MODIFIER",)),
            (re.compile("<FUNC_degreeHead>[當蓋]</FUNC_degreeHead><ACTION_verb>[^<驚]+</ACTION_verb>"), ("ACTION_verb",), ("MODIFIER",)),
            (re.compile("<FUNC_degreeHead>[^<]+</FUNC_degreeHead><MODIFIER>[^<]+</MODIFIER>"),("</FUNC_degreeHead><MODIFIER>", "<FUNC_degreeHead>", "</MODIFIER>"), ("", "<DegreeP>", "</DegreeP>")),
            (re.compile("<ACTION_verb>[^<]+</ACTION_verb><ACTION_verb>起來</ACTION_verb>"), ("</ACTION_verb><ACTION_verb>",), ("",)),
            (re.compile("<ACTION_verb>[^<會]+</ACTION_verb><ACTION_verb>[著到]</ACTION_verb>"), ("</ACTION_verb><ACTION_verb>",), ("",)),
            (re.compile("<ASPECT>忒</ASPECT><MODIFIER>[^<]+</MODIFIER>"),("</ASPECT><MODIFIER>", "ASPECT", "MODIFIER"), ("", "DegreeP", "DegreeP")),
            (re.compile("<ACTION_verb>[斷脫]</ACTION_verb><ASPECT>[忒核]</ASPECT>"),("</ACTION_verb><ASPECT>", "ASPECT",), ("", "ACTION_verb")),
            (re.compile("(?<=</ENTITY_num>)<ENTITY_noun>個人</ENTITY_noun>"),("<ENTITY_noun>個人</ENTITY_noun>",), ("<ENTITY_classifier>個</ENTITY_classifier><ENTITY_noun>人</ENTITY_noun>",)),
            (re.compile("(?<=</FUNC_degreeHead>)<ACTION_verb>好</ACTION_verb>"), ("ACTION_verb",), ("MODIFIER",)),
            (re.compile("<ACTION_verb>[^<]+</ACTION_verb><MODIFIER>飽</MODIFIER>"),("</ACTION_verb><MODIFIER>","MODIFIER"), ("","ACTION_verb")),
            (re.compile("(?<=</ACTION_verb>)<TIME_day>夜</TIME_day>"),("TIME_day",), ("ENTITY_noun",)),
            (re.compile("<ASPECT>好</ASPECT>(?=<CLAUSE_Q>)"),("ASPECT",), ("ACTION_verb",)),
            (re.compile("<ACTION_verb>[上下]</ACTION_verb><ENTITY_noun>禮拜</ENTITY_noun>"),("</ACTION_verb><ENTITY_noun>","ACTION_verb","ENTITY_noun"), ("","TIME_justtime","TIME_justtime")),
            (re.compile("(<ACTION_verb>好</ACTION_verb>)<QUANTIFIER>歸</QUANTIFIER>"),("QUANTIFIER",), ("ACTION_verb",)),
            (re.compile("(?<=</ENTITY_classifier>)<ACTION_verb>妄想</ACTION_verb>"),("ACTION_verb",), ("ENTITY_noun",)),
            (re.compile("<FUNC_degreeHead>[恁盡過當蓋]</FUNC_degreeHead>(?=<ACTION_verb>)"),("FUNC_degreeHead",), ("MODIFIER",)),
            (re.compile("<ACTION_verb>打</ACTION_verb><ACTION_verb>結</ACTION_verb>"),("</ACTION_verb><ACTION_verb>",), ("",)),
            (re.compile("<DegreeP>盡好</DegreeP><ACTION_verb>食</ACTION_verb>"),("DegreeP",), ("ACTION_verb",)),
            (re.compile("(?<=擺</ENTITY_classifier>)<ACTION_verb>旅行</ACTION_verb>"),("ACTION_verb",), ("ENTITY_noun",)),
            (re.compile("<ACTION_verb>包</ACTION_verb>(?=<ENTITY_noun>)"),("ACTION_verb",), ("ENTITY_classifier",)),
            (re.compile("(<FUNC_determiner>這</FUNC_determiner>)<ACTION_verb>[領袋]</ACTION_verb>"),("ACTION_verb",), ("ENTITY_classifier",)),
            (re.compile("(<FUNC_determiner>[這該]</FUNC_determiner>)<QUANTIFIER>兜</QUANTIFIER>"),("QUANTIFIER",), ("ENTITY_classifier",)),
            (re.compile("<FUNC_determiner>[^<]+</FUNC_determiner><ENTITY_classifier>[^<]+</ENTITY_classifier>"),("</FUNC_determiner><ENTITY_classifier>","FUNC_determiner","ENTITY_classifier"), ("","ENTITY_DetPhrase","ENTITY_DetPhrase")),
            (re.compile("<ENTITY_pronoun>[^<]+</ENTITY_pronoun>(?=<ENTITY_pronoun>)"),("ENTITY_pronoun",), ("ENTITY_possessive",)),
            (re.compile("<FUNC_inter>無</FUNC_inter><ENTITY_noun>[人風雨]</ENTITY_noun>"),("FUNC_inter",), ("FUNC_negation",)),
            (re.compile("<ACTION_verb>[^<愛]+</ACTION_verb><ACTION_verb>[出來下來入]+</ACTION_verb>"),("</ACTION_verb><ACTION_verb>",), ("",)),
            (re.compile("<ENTITY_person>錢放</ENTITY_person>"),("<ENTITY_person>錢放</ENTITY_person>",), ("<ENTITY_noun>錢</ENTITY_noun><ACTION_verb>放</ACTION_verb>",)),
            (re.compile("<ENTITY_noun>[^<]+</ENTITY_noun><ENTITY_classifier>頂</ENTITY_classifier>"),("ENTITY_classifier",), ("RANGE_locality",)),
            (re.compile("<MODIFIER>毋好</MODIFIER>(?=<ACTION_verb>)"),("MODIFIER",), ("FUNC_negation",)),
            (re.compile("<ACTION_verb>晒</ACTION_verb><ENTITY_noun>日頭</ENTITY_noun>"),("</ACTION_verb><ENTITY_noun>","</ENTITY_noun>"), ("","</ACTION_verb>")),
            (re.compile("<ACTION_verb>打開</ACTION_verb><ACTION_verb>來</ACTION_verb>"),("</ACTION_verb><ACTION_verb>",), ("",)),
            (re.compile("<MODIFIER>([^<])</MODIFIER><MODIFIER>\\1</MODIFIER>"), ("</MODIFIER><MODIFIER>",), ("",)),
            (re.compile("<ACTION_verb>[關擎]</ACTION_verb><ASPECT>好</ASPECT>"), ("ASPECT",), ("MODIFIER",)),
            (re.compile("<TIME_justtime>過後</TIME_justtime><ACTION_verb>背</ACTION_verb>"), ("<TIME_justtime>過後</TIME_justtime><ACTION_verb>背</ACTION_verb>",), ("<FUNC_degreeHead>過</FUNC_degreeHead><RANGE_locality>後背</RANGE_locality>",)),
            (re.compile("<ACTION_verb>[^<]+</ACTION_verb><ACTION_verb>去</ACTION_verb>"), ("</ACTION_verb><ACTION_verb>",), ("",)),
            (re.compile("<ACTION_verb>逐</ACTION_verb><ENTITY_noun>禮拜</ENTITY_noun>"), ("</ACTION_verb><ENTITY_noun>","ACTION_verb","ENTITY_noun"), ("","TIME_justtime","TIME_justtime")),
            (re.compile("<MODIFIER>每</MODIFIER><ENTITY_noun>禮拜</ENTITY_noun>"), ("</MODIFIER><ENTITY_noun>","MODIFIER","ENTITY_noun"), ("","TIME_justtime","TIME_justtime")),
            (re.compile("(?<=</ASPECT>)<ASPECT>等</ASPECT>"), ("ASPECT",), ("ACTION_verb",)),
            (re.compile("<ENTITY_pronoun>𠊎等</ENTITY_pronoun><TIME_justtime>一下</TIME_justtime>"), ("<ENTITY_pronoun>𠊎等</ENTITY_pronoun><TIME_justtime>一下</TIME_justtime>",), ("<ENTITY_pronoun>𠊎</ENTITY_pronoun><TIME_justtime>等一下</TIME_justtime>",)),
            (re.compile("<ENTITY_pronoun>𠊎等</ENTITY_pronoun><ACTION_verb>下來</ACTION_verb>"), ("<ENTITY_pronoun>𠊎等</ENTITY_pronoun><ACTION_verb>下來</ACTION_verb>",), ("<ENTITY_pronoun>𠊎</ENTITY_pronoun><TIME_justtime>等下</TIME_justtime><ACTION_verb>來</ACTION_verb>",)),
            (re.compile("<FUNC_degreeHead>過</FUNC_degreeHead><ENTITY_noun>[^<]+</ENTITY_noun>"), ("FUNC_degreeHead",), ("ACTION_verb",)),
            (re.compile("(<ACTION_verb>看</ACTION_verb><FUNC_negation>毋</FUNC_negation>)<ACTION_verb>著</ACTION_verb>"), ("ACTION_verb",), ("MODIFIER",)),
            (re.compile("<MODAL>正</MODAL><ACTION_verb>著</ACTION_verb>"), ("ACTION_verb",), ("MODIFIER",)),
            (re.compile("<MODIFIER>罅</MODIFIER><MODIFIER>[^<]+</MODIFIER>"), ("</MODIFIER><MODIFIER>",), ("",)),
            (re.compile("<CLAUSE_particle>([^<])</CLAUSE_particle><CLAUSE_particle>\\1</CLAUSE_particle>"), ("</CLAUSE_particle><CLAUSE_particle>",), ("",)),
            (re.compile("<ACTION_verb>著</ACTION_verb>(<ENTITY_oov>片</ENTITY_oov>)"), ("ACTION_verb",), ("MODIFIER",)),
            (re.compile("(<FUNC_inter>無</FUNC_inter>)<QUANTIFIER>歸</QUANTIFIER>"), ("QUANTIFIER",), ("ACTION_verb",)),
            (re.compile("<ENTITY_noun>鉛筆</ENTITY_noun><ENTITY_noun>盒仔</ENTITY_noun>"), ("</ENTITY_noun><ENTITY_noun>",), ("",)),
            (re.compile("<QUANTIFIER>兜</QUANTIFIER><ENTITY_classifier>[^<]+</ENTITY_classifier>"), ("QUANTIFIER",), ("ACTION_verb",)),
            (re.compile("<QUANTIFIER>歸</QUANTIFIER><ENTITY_noun>個人</ENTITY_noun>"), ("<QUANTIFIER>歸</QUANTIFIER><ENTITY_noun>個人</ENTITY_noun>",), ("<ENTITY_DetPhrase>歸個</ENTITY_DetPhrase><ENTITY_noun>人</ENTITY_noun>",)),
            (re.compile("<ACTION_verb>著</ACTION_verb><FUNC_conjunction>抑</FUNC_conjunction><FUNC_negation>毋</FUNC_negation><ACTION_verb>著</ACTION_verb>"), ("ACTION_verb",), ("MODIFIER",)),
            (re.compile("<ACTION_verb>寫</ACTION_verb><FUNC_negation>毋</FUNC_negation><ACTION_verb>著</ACTION_verb>"), ("<ACTION_verb>著</ACTION_verb>",), ("<MODIFIER>著</MODIFIER>",)),
            (re.compile("<ENTITY_classifier>有兜</ENTITY_classifier>"), ("<ENTITY_classifier>有兜</ENTITY_classifier>",), ("<ACTION_verb>有</ACTION_verb><QUANTIFIER>兜</QUANTIFIER>",)),
            (re.compile("(<ACTION_verb>有</ACTION_verb>)<QUANTIFIER>兜</QUANTIFIER><FUNC_inner>仔</FUNC_inner>"), ("</QUANTIFIER><FUNC_inner>","FUNC_inner",), ("","QUANTIFIER",)),
            (re.compile("<ACTION_verb>壞</ACTION_verb><MODIFIER>淨淨</MODIFIER>"), ("</ACTION_verb><MODIFIER>","ACTION_verb",), ("","MODIFIER",)),
            (re.compile("<MODIFIER_color>[^<]+</MODIFIER_color><ENTITY_noun>色</ENTITY_noun>"), ("</MODIFIER_color><ENTITY_noun>","ENTITY_noun",), ("","MODIFIER_color",)),
            (re.compile("<ACTION_verb>食</ACTION_verb><ACTION_verb>壞</ACTION_verb>"), ("</ACTION_verb><ACTION_verb>",), ("",)),
            (re.compile("<DegreeP>還細</DegreeP><MODIFIER>細</MODIFIER>"), ("<DegreeP>還細</DegreeP><MODIFIER>細</MODIFIER>",), ("<FUNC_inner>還</FUNC_inner><MODIFIER>細細</MODIFIER>",)),
            (re.compile("<ENTITY_person>毋知愛</ENTITY_person>"), ("<ENTITY_person>毋知愛</ENTITY_person>",), ("<FUNC_negation>毋</FUNC_negation><ACTION_verb>知</ACTION_verb><ACTION_verb>愛</ACTION_verb>",)),
            (re.compile("<DegreeP>恁大</DegreeP><ENTITY_noun>力</ENTITY_noun>"), ("</DegreeP><ENTITY_noun>","ENTITY_noun",), ("","DegreeP",)),
]